#!/usr/bin/env bash
# commit-guard — pre-push enforcement for ba-00001 (profile README).
#
# SOURCE OF TRUTH: .claude/agents/commit-guard.md (the agent spec). This script
# is the executable mirror of that file — when the .md rules change (patterns,
# identities), regenerate/sync this script to match. Rule rationale lives in
# the private guide repo (projectguidefordev).
# This script just enforces the rules automatically so a bad push can't slip out.
#
# HARD checks (block the push, exit 1):
#   1. author email must be the ba-00001 noreply address
#   2. no AI/tool/bot attribution in commit messages being pushed
#   3. every commit's author + committer is an allowed ba-00001 identity
# SOFT checks (warn only):
#   4. attribution-specific words in added diff lines
#
# Installed as .git/hooks/pre-push by scripts/install-git-hooks.sh.
# Override in a pinch with:  git push --no-verify

set -uo pipefail

EXPECTED_EMAIL="124537281+ba-00001@users.noreply.github.com"
ZERO="0000000000000000000000000000000000000000"
fail=0

red() { printf '\033[31m%s\033[0m\n' "$1"; }
grn() { printf '\033[32m%s\033[0m\n' "$1"; }
ylw() { printf '\033[33m%s\033[0m\n' "$1"; }

# --- figure out which commits are being pushed -----------------------------
# pre-push feeds "<local_ref> <local_sha> <remote_ref> <remote_sha>" on stdin.
# Run by hand (tty) it falls back to "everything not yet on origin".
ranges=()
if [ ! -t 0 ]; then
  while read -r local_ref local_sha remote_ref remote_sha; do
    [ -z "${local_sha:-}" ] && continue
    [ "$local_sha" = "$ZERO" ] && continue            # branch deletion
    if [ "${remote_sha:-$ZERO}" = "$ZERO" ]; then
      ranges+=("$local_sha --not --remotes=origin")   # new branch
    else
      ranges+=("$remote_sha..$local_sha")
    fi
  done
fi
if [ ${#ranges[@]} -eq 0 ]; then
  if git rev-parse --abbrev-ref --symbolic-full-name '@{u}' >/dev/null 2>&1; then
    ranges+=("@{u}..HEAD")
  else
    ranges+=("HEAD --not --remotes=origin")
  fi
fi
# shellcheck disable=SC2086
commits="$(for r in "${ranges[@]}"; do git rev-list $r; done 2>/dev/null | sort -u)"

# --- 1. author email (HARD) ------------------------------------------------
email="$(git config user.email || true)"
if [ "$email" != "$EXPECTED_EMAIL" ]; then
  red "HARD FAIL · author email is '$email' (expected $EXPECTED_EMAIL)"
  echo "    fix: git config user.email \"$EXPECTED_EMAIL\""
  fail=1
fi

if [ -z "$commits" ]; then
  [ "$fail" -eq 0 ] && grn "commit-guard: no new commits to scan; email OK"
  exit "$fail"
fi

# --- 2. forbidden attribution in commit messages (HARD) --------------------
# AI-name tokens are matched as ATTRIBUTION only: a leading (^|[^.[:alnum:]])
# guard means a preceding dot or letter excludes them, so the literal ".claude/"
# config-dir path in a message/diff is NOT flagged, but "Claude Code" / "by
# Claude" / a co-author trailer still is.
MSG_PAT='co-authored-by:|generated with|generated by|auto-generated|🤖|🦾|\[bot\]|(^|[^.[:alnum:]])(claude|anthropic|chatgpt|gpt-|copilot|llm)'
while read -r c; do
  [ -z "$c" ] && continue
  hits="$(git log -1 --format='%s%n%b' "$c" | grep -iEn "$MSG_PAT" || true)"
  if [ -n "$hits" ]; then
    red "HARD FAIL · forbidden attribution in commit ${c:0:9} message"
    printf '%s\n' "$hits" | sed 's/^/    /'
    fail=1
  fi
done <<< "$commits"

# --- 3. author / committer identity (HARD) ---------------------------------
ID_OK='^(ba-00001|BRIAN BAZURTO|Brian Bazurto) <124537281\+ba-00001@users\.noreply\.github\.com>$'
while read -r c; do
  [ -z "$c" ] && continue
  while read -r who; do
    if ! printf '%s' "$who" | grep -qE "$ID_OK"; then
      red "HARD FAIL · disallowed identity in commit ${c:0:9}: $who"
      echo "    fix: reauthor to 'ba-00001 <$EXPECTED_EMAIL>'"
      fail=1
    fi
  done < <(git log -1 --format='%an <%ae>%n%cn <%ce>' "$c")
done <<< "$commits"

# --- 4. SOFT: attribution words in added diff lines ------------------------
DIFF_PAT='co-authored-by:|🤖|🦾|generated with|generated by|auto-generated|(^|[^.[:alnum:]])(claude|anthropic|copilot)'
cur=""
while read -r c; do
  [ -z "$c" ] && continue
  while IFS= read -r line; do
    case "$line" in
      "diff --git a/"*) cur="${line#diff --git a/}"; cur="${cur%% b/*}" ;;
      "+++"*) ;;
      "+"*)
        if printf '%s' "$line" | grep -iqE "$DIFF_PAT"; then
          ylw "SOFT WARN · $cur: $(printf '%s' "${line#+}" | cut -c1-80)"
        fi
        ;;
    esac
  done < <(git show --format= --unified=0 "$c")
done <<< "$commits"

if [ "$fail" -eq 1 ]; then
  red "commit-guard: PUSH BLOCKED — fix the HARD FAILs above (or 'git push --no-verify')."
  exit 1
fi
grn "commit-guard: PASS"
exit 0
